### ISSUE TITLE
2017.02.28 目前进度

### ISSUE THREAD

**Issue by Kinghsy** [Kinghsy/490_core#3]
BFS+DFS的方法已经写好了，test也做好了过了（就是目测为没什么问题）
然后simulation的代码和结果明天早上就能改然后我会作一下分析然后pou上来
概率的修改方法上我觉得还有必要再斟酌一下
然后profile方面我会参考

**Comment by tripack45** [comment]
很强。thx

**Comment by tripack45** [comment]
有明显的速度提升么
